name: CI

on: [push, pull_request]

jobs:
  ios-sdl:
    runs-on: macos-12
    env:
      SDL_VERSION: 2.26.5
      SDL_TTF_VERSION: 2.0.18
    steps:
      - name: Checkout TGUI
        uses: actions/checkout@v3

      - name: Build SDL
        run: |
          wget -nv https://github.com/libsdl-org/SDL/releases/download/release-$SDL_VERSION/SDL2-$SDL_VERSION.zip
          unzip SDL2-$SDL_VERSION.zip
          xcodebuild -project SDL2-$SDL_VERSION/Xcode/SDL/SDL.xcodeproj -scheme "Static Library-iOS" CONFIGURATION_BUILD_DIR="$GITHUB_WORKSPACE/SDL-iOS-libs"

      - name: Build SDL_ttf
        run: |
          wget -nv https://github.com/libsdl-org/SDL_ttf/releases/download/release-$SDL_TTF_VERSION/SDL2_ttf-$SDL_TTF_VERSION.zip
          unzip SDL2_ttf-$SDL_TTF_VERSION.zip
          xcodebuild -project SDL2_ttf-$SDL_TTF_VERSION/Xcode/SDL_ttf.xcodeproj -scheme "Static Library" CONFIGURATION_BUILD_DIR="$GITHUB_WORKSPACE/SDL-iOS-libs"

      - name: Build TGUI (SDL_RENDERER)
        run: >
          cmake -B TGUI-build-iOS-SDL_RENDERER
          -GXcode
          -DCMAKE_SYSTEM_NAME=iOS
          -DCMAKE_OSX_ARCHITECTURES=arm64
          -DCMAKE_OSX_DEPLOYMENT_TARGET=15.0
          -DTGUI_BACKEND=SDL_RENDERER
          -DTGUI_SHARED_LIBS=OFF
          -DCMAKE_UNITY_BUILD=ON
          -DTGUI_CXX_STANDARD=17
          -DTGUI_WARNINGS_AS_ERRORS=ON
          -DTGUI_BUILD_EXAMPLES=OFF
          -DSDL2_LIBRARY=/Users/texus/Desktop/iOS-libs/libSDL2.a
          -DSDL2_INCLUDE_DIR=/Users/texus/Desktop/SDL/include
          -DSDL2_TTF_LIBRARY=/Users/texus/Desktop/iOS-libs/libSDL2_ttf.a
          -DSDL2_TTF_INCLUDE_DIR=/Users/texus/Desktop/SDL_ttf
          -DTGUI_SKIP_SDL_CONFIG=TRUE

          xcodebuild -project TGUI-build-iOS-SDL_RENDERER/TGUI.xcodeproj -target ALL_BUILD -configuration Release CONFIGURATION_BUILD_DIR="$GITHUB_WORKSPACE/TGUI-iOS-lib"

          test -e TGUI-iOS-lib/libtgui-s.a

      - name: Build TGUI (SDL_TTF_GLES2)
        run: >
          cmake -B TGUI-build-iOS-SDL_TTF_GLES2
          -GXcode
          -DCMAKE_SYSTEM_NAME=iOS
          -DCMAKE_OSX_ARCHITECTURES=arm64
          -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0
          -DCMAKE_INSTALL_PREFIX=TGUI_INSTALL
          -DTGUI_BACKEND=SDL_TTF_GLES2
          -DTGUI_SHARED_LIBS=OFF
          -DCMAKE_UNITY_BUILD=ON
          -DTGUI_CXX_STANDARD=17
          -DTGUI_WARNINGS_AS_ERRORS=ON
          -DTGUI_BUILD_EXAMPLES=OFF
          -DSDL2_LIBRARY=/Users/texus/Desktop/iOS-libs/libSDL2.a
          -DSDL2_INCLUDE_DIR=/Users/texus/Desktop/SDL/include
          -DSDL2_TTF_LIBRARY=/Users/texus/Desktop/iOS-libs/libSDL2_ttf.a
          -DSDL2_TTF_INCLUDE_DIR=/Users/texus/Desktop/SDL_ttf
          -DTGUI_SKIP_SDL_CONFIG=TRUE

          cmake --build TGUI-build-iOS-SDL_TTF_GLES2 --config Release --target install

          ls

          ls TGUI_INSTALL

          ls TGUI_INSTALL/lib

          test -e TGUI_INSTALL/lib/libtgui-s.a

